name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./fieldsOfScience/postProcessing.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.datacite.org/graphql
          downloaded_filename: ./fieldsOfScience/fieldsOfScience.csv
          axios_config: ./fieldsOfScience/query.json
          postprocess: ./fieldsOfScience/postProcessing.js
